#!/usr/bin/env python3
"""
Configuration wizard for OverWatch alerts.
Helps set up email and Telegram notifications interactively.
"""

import json
import os
from pathlib import Path
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.panel import Panel
from rich.table import Table

console = Console()


def get_config_dir():
    """Get the configuration directory path."""
    return os.path.join(os.path.dirname(__file__), "overwatch", "alerts")


def load_thresholds():
    """Load current threshold configuration."""
    config_path = os.path.join(get_config_dir(), "thresholds.json")
    try:
        with open(config_path, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        return {
            "cpu": {"threshold": 90, "enabled": True},
            "memory": {"threshold": 80, "enabled": True},
            "disk": {"threshold": 85, "enabled": True},
            "temperature": {"threshold": 80, "enabled": False},
        }


def save_thresholds(config):
    """Save threshold configuration."""
    config_path = os.path.join(get_config_dir(), "thresholds.json")
    with open(config_path, 'w') as f:
        json.dump(config, f, indent=2)
    console.print(f"[green]✓ Thresholds saved to {config_path}[/green]")


def configure_thresholds():
    """Interactive threshold configuration."""
    console.print(Panel.fit(
        "[bold cyan]Configure Alert Thresholds[/bold cyan]\n"
        "Set when alerts should be triggered",
        border_style="cyan"
    ))
    console.print()
    
    config = load_thresholds()
    
    # Display current thresholds
    table = Table(title="Current Thresholds")
    table.add_column("Metric", style="cyan")
    table.add_column("Threshold", style="yellow")
    table.add_column("Enabled", style="green")
    
    for metric, settings in config.items():
        table.add_row(
            metric.upper(),
            f"{settings['threshold']}%",
            "✓" if settings['enabled'] else "✗"
        )
    
    console.print(table)
    console.print()
    
    if Confirm.ask("Do you want to modify thresholds?", default=False):
        console.print()
        
        for metric in ["cpu", "memory", "disk", "temperature"]:
            console.print(f"[cyan]Configure {metric.upper()}[/cyan]")
            
            # Enable/disable
            enabled = Confirm.ask(
                f"  Enable {metric} monitoring?",
                default=config.get(metric, {}).get("enabled", True)
            )
            
            if enabled:
                # Set threshold
                current = config.get(metric, {}).get("threshold", 80)
                threshold = Prompt.ask(
                    f"  Alert threshold (0-100)",
                    default=str(current)
                )
                
                try:
                    threshold = int(threshold)
                    if 0 <= threshold <= 100:
                        config[metric] = {"threshold": threshold, "enabled": True}
                    else:
                        console.print("  [red]Invalid threshold, keeping previous value[/red]")
                except ValueError:
                    console.print("  [red]Invalid number, keeping previous value[/red]")
            else:
                config[metric] = {
                    "threshold": config.get(metric, {}).get("threshold", 80),
                    "enabled": False
                }
            
            console.print()
        
        save_thresholds(config)
    else:
        console.print("[yellow]Keeping current thresholds[/yellow]")


def create_env_file(env_vars):
    """Create .env file with configuration."""
    env_path = os.path.join(os.path.dirname(__file__), ".env")
    
    with open(env_path, 'w') as f:
        f.write("# OverWatch Configuration\n")
        f.write("# Generated by config wizard\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    console.print(f"[green]✓ Configuration saved to {env_path}[/green]")


def configure_email():
    """Interactive email configuration."""
    console.print(Panel.fit(
        "[bold cyan]Configure Email Notifications[/bold cyan]\n"
        "Set up SMTP server for email alerts",
        border_style="cyan"
    ))
    console.print()
    
    env_vars = {}
    
    # SMTP Server
    console.print("[yellow]Common SMTP Servers:[/yellow]")
    console.print("  Gmail: smtp.gmail.com (port 587)")
    console.print("  Outlook: smtp-mail.outlook.com (port 587)")
    console.print("  Yahoo: smtp.mail.yahoo.com (port 587)")
    console.print()
    
    server = Prompt.ask("SMTP Server", default="smtp.gmail.com")
    port = Prompt.ask("SMTP Port", default="587")
    
    env_vars["EMAIL_SMTP_SERVER"] = server
    env_vars["EMAIL_SMTP_PORT"] = port
    
    # Credentials
    console.print()
    console.print("[yellow]Note: For Gmail, use an App Password, not your regular password[/yellow]")
    console.print("[yellow]Generate one at: https://myaccount.google.com/apppasswords[/yellow]")
    console.print()
    
    username = Prompt.ask("SMTP Username (email address)")
    password = Prompt.ask("SMTP Password", password=True)
    
    env_vars["EMAIL_SMTP_USERNAME"] = username
    env_vars["EMAIL_SMTP_PASSWORD"] = password
    
    # From/To addresses
    from_email = Prompt.ask("From Email", default=username)
    to_email = Prompt.ask("To Email (recipient)", default=username)
    
    env_vars["EMAIL_FROM"] = from_email
    env_vars["EMAIL_TO"] = to_email
    
    return env_vars


def configure_telegram():
    """Interactive Telegram configuration."""
    console.print(Panel.fit(
        "[bold cyan]Configure Telegram Notifications[/bold cyan]\n"
        "Set up Telegram bot for alerts",
        border_style="cyan"
    ))
    console.print()
    
    console.print("[yellow]To create a Telegram bot:[/yellow]")
    console.print("1. Message @BotFather on Telegram")
    console.print("2. Send /newbot and follow instructions")
    console.print("3. Copy the bot token")
    console.print()
    console.print("[yellow]To get your Chat ID:[/yellow]")
    console.print("1. Message @userinfobot on Telegram")
    console.print("2. Copy your Chat ID")
    console.print()
    
    env_vars = {}
    
    bot_token = Prompt.ask("Telegram Bot Token")
    chat_id = Prompt.ask("Telegram Chat ID")
    
    env_vars["TELEGRAM_BOT_TOKEN"] = bot_token
    env_vars["TELEGRAM_CHAT_ID"] = chat_id
    
    return env_vars


def test_email_config(env_vars):
    """Test email configuration."""
    console.print("\n[cyan]Testing email configuration...[/cyan]")
    
    # Set environment variables temporarily
    for key, value in env_vars.items():
        os.environ[key] = value
    
    try:
        from overwatch.alerts.email import EmailNotifier
        
        notifier = EmailNotifier()
        
        if notifier.test_connection():
            console.print("[green]✓ Email configuration is working![/green]")
            
            if Confirm.ask("Send a test alert email?", default=True):
                notifier.send_alert(
                    "test",
                    "This is a test alert from OverWatch configuration wizard",
                    42.0
                )
                console.print("[green]✓ Test email sent![/green]")
        else:
            console.print("[red]✗ Email configuration failed. Please check your settings.[/red]")
    except Exception as e:
        console.print(f"[red]✗ Error: {e}[/red]")


def test_telegram_config(env_vars):
    """Test Telegram configuration."""
    console.print("\n[cyan]Testing Telegram configuration...[/cyan]")
    
    # Set environment variables temporarily
    for key, value in env_vars.items():
        os.environ[key] = value
    
    try:
        from overwatch.alerts.telegram import TelegramNotifier
        
        notifier = TelegramNotifier()
        
        if notifier.test_connection():
            console.print("[green]✓ Telegram configuration is working![/green]")
            
            if Confirm.ask("Send a test alert message?", default=True):
                notifier.send_alert(
                    "test",
                    "This is a test alert from OverWatch configuration wizard",
                    42.0
                )
                console.print("[green]✓ Test message sent![/green]")
        else:
            console.print("[red]✗ Telegram configuration failed. Please check your settings.[/red]")
    except Exception as e:
        console.print(f"[red]✗ Error: {e}[/red]")


def main():
    """Main configuration wizard."""
    console.print(Panel.fit(
        "[bold cyan]OverWatch Configuration Wizard[/bold cyan]\n"
        "Set up alerts and notifications",
        border_style="cyan"
    ))
    console.print()
    
    # Configure thresholds
    configure_thresholds()
    console.print()
    
    # Configure notifications
    all_env_vars = {}
    
    if Confirm.ask("Configure email notifications?", default=True):
        console.print()
        email_vars = configure_email()
        all_env_vars.update(email_vars)
        
        if Confirm.ask("\nTest email configuration now?", default=True):
            test_email_config(email_vars)
    
    console.print()
    
    if Confirm.ask("Configure Telegram notifications?", default=False):
        console.print()
        telegram_vars = configure_telegram()
        all_env_vars.update(telegram_vars)
        
        if Confirm.ask("\nTest Telegram configuration now?", default=True):
            test_telegram_config(telegram_vars)
    
    # Save configuration
    if all_env_vars:
        console.print()
        if Confirm.ask("Save configuration to .env file?", default=True):
            create_env_file(all_env_vars)
            console.print()
            console.print("[yellow]To use this configuration, run:[/yellow]")
            console.print("[cyan]  source .env[/cyan]")
            console.print("[cyan]  export $(cat .env | xargs)[/cyan]")
    
    console.print()
    console.print(Panel.fit(
        "[bold green]Configuration Complete![/bold green]\n\n"
        "Your OverWatch is now configured for alerts.\n"
        "Start monitoring with: [cyan]overwatch start[/cyan]",
        border_style="green"
    ))


if __name__ == "__main__":
    main()
