"""
Email notification handler for OverWatch alerts.
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional


class EmailNotifier:
    """Send alerts via email."""
    
    def __init__(
        self,
        smtp_server: Optional[str] = None,
        smtp_port: Optional[int] = None,
        smtp_username: Optional[str] = None,
        smtp_password: Optional[str] = None,
        from_email: Optional[str] = None,
        to_email: Optional[str] = None,
    ):
        """
        Initialize email notifier.
        
        Args:
            smtp_server: SMTP server address (or set EMAIL_SMTP_SERVER env var)
            smtp_port: SMTP port (or set EMAIL_SMTP_PORT env var, default: 587)
            smtp_username: SMTP username (or set EMAIL_SMTP_USERNAME env var)
            smtp_password: SMTP password (or set EMAIL_SMTP_PASSWORD env var)
            from_email: From email address (or set EMAIL_FROM env var)
            to_email: To email address (or set EMAIL_TO env var)
        """
        self.smtp_server = smtp_server or os.getenv("EMAIL_SMTP_SERVER")
        self.smtp_port = smtp_port or int(os.getenv("EMAIL_SMTP_PORT", "587"))
        self.smtp_username = smtp_username or os.getenv("EMAIL_SMTP_USERNAME")
        self.smtp_password = smtp_password or os.getenv("EMAIL_SMTP_PASSWORD")
        self.from_email = from_email or os.getenv("EMAIL_FROM")
        self.to_email = to_email or os.getenv("EMAIL_TO")
        
        self.enabled = bool(
            self.smtp_server
            and self.smtp_username
            and self.smtp_password
            and self.from_email
            and self.to_email
        )
        
        if not self.enabled:
            print("Warning: Email notifier not configured. Set required environment variables.")
    
    def send_alert(self, alert_type: str, message: str, value: float):
        """
        Send an alert via email.
        
        Args:
            alert_type: Type of alert
            message: Alert message
            value: Current value
        """
        if not self.enabled:
            return
        
        subject = f"OverWatch Alert: {alert_type.upper()}"
        
        # Create HTML email body
        html_body = f"""
        <html>
            <head></head>
            <body>
                <h2 style="color: #e74c3c;">⚠️ OverWatch Alert</h2>
                <p><strong>Type:</strong> {alert_type.upper()}</p>
                <p><strong>Message:</strong> {message}</p>
                <p><strong>Value:</strong> {value}</p>
                <hr>
                <p style="color: #7f8c8d; font-size: 12px;">
                    This alert was generated by OverWatch system monitor.
                </p>
            </body>
        </html>
        """
        
        # Create plain text alternative
        text_body = f"""
        OverWatch Alert
        
        Type: {alert_type.upper()}
        Message: {message}
        Value: {value}
        
        ---
        This alert was generated by OverWatch system monitor.
        """
        
        try:
            # Create message
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = self.from_email
            msg["To"] = self.to_email
            
            # Attach both plain text and HTML versions
            part1 = MIMEText(text_body, "plain")
            part2 = MIMEText(html_body, "html")
            msg.attach(part1)
            msg.attach(part2)
            
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_username, self.smtp_password)
                server.send_message(msg)
                
        except Exception as e:
            print(f"Error sending email notification: {e}")
    
    def test_connection(self) -> bool:
        """
        Test email server connection.
        
        Returns:
            True if connection successful
        """
        if not self.enabled:
            return False
        
        try:
            with smtplib.SMTP(self.smtp_server, self.smtp_port, timeout=10) as server:
                server.starttls()
                server.login(self.smtp_username, self.smtp_password)
                return True
        except Exception:
            return False
